import type { components, paths } from './schema';

export type Paths = paths;
export type Schemas = components['schemas'];

export type StatusResponse = Schemas['StatusResponse'];
export type GlobalStats = Schemas['GlobalStats'];
export type ClientStats = Schemas['ClientStats'];
export type UpstreamStats = Schemas['UpstreamStats'];
export type QueryLogEntry = Schemas['QueryLogEntry'];
export type QueryLogPage = Schemas['QueryLogPage'];
export type FilterListDto = Schemas['FilterListDto'];
export type CustomRulesDto = Schemas['CustomRulesDto'];
export type FilterCheckRequest = Schemas['FilterCheckRequest'];
export type FilterCheckResponse = Schemas['FilterCheckResponse'];
export type ClientDto = Schemas['ClientDto'];
export type ClientGroupDto = Schemas['ClientGroupDto'];
export type RewriteDto = Schemas['RewriteDto'];
export type AddRewriteRequest = Schemas['AddRewriteRequest'];
export type UpstreamConfigDto = Schemas['UpstreamConfigDto'];
export type UpstreamTestRequest = Schemas['UpstreamTestRequest'];
export type UpstreamTestResponse = Schemas['UpstreamTestResponse'];
export type UpstreamTestItem = Schemas['UpstreamTestItem'];
export type ConfigResponse = Schemas['ConfigResponse'];
export type UpdateConfigRequest = Schemas['UpdateConfigRequest'];
export type ApiTokenMeta = Schemas['ApiTokenMeta'];
export type CreateTokenRequest = Schemas['CreateTokenRequest'];
export type CreateTokenResponse = Schemas['CreateTokenResponse'];
export type TotpSetupResponse = Schemas['TotpSetupResponse'];
export type TotpConfirmRequest = Schemas['TotpConfirmRequest'];
export type LoginRequest = Schemas['LoginRequest'];
export type LoginResponse = Schemas['LoginResponse'];
export type ProblemDetails = Schemas['ProblemDetails'];
export type AddFilterListRequest = Schemas['AddFilterListRequest'];
export type UpdateFilterListRequest = Schemas['UpdateFilterListRequest'];
export type RestorePreparedResponse = Schemas['RestorePreparedResponse'];
export type RestoreConfirmRequest = Schemas['RestoreConfirmRequest'];
export type Role = Schemas['Role'];
