//! OpenAPI specification generator via utoipa.

use utoipa::OpenApi;

/// Root OpenAPI documentation specification for the sito administration API.
#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::status::get_status,
        crate::handlers::stats::get_stats,
        crate::handlers::stats::get_client_stats,
        crate::handlers::stats::get_upstream_stats,
        crate::handlers::querylog::get_querylog,
        crate::handlers::querylog::delete_querylog,
        crate::handlers::filtering::get_filter_lists,
        crate::handlers::filtering::add_filter_list,
        crate::handlers::filtering::update_filter_list,
        crate::handlers::filtering::delete_filter_list,
        crate::handlers::filtering::refresh_filtering,
        crate::handlers::filtering::get_filtering_rules,
        crate::handlers::filtering::set_filtering_rules,
        crate::handlers::filtering::check_filtering,
        crate::handlers::clients::get_clients,
        crate::handlers::clients::create_client,
        crate::handlers::clients::update_client,
        crate::handlers::clients::delete_client,
        crate::handlers::clients::get_client_groups,
        crate::handlers::clients::add_client_group,
        crate::handlers::clients::update_client_group,
        crate::handlers::clients::delete_client_group,
        crate::handlers::rewrites::get_rewrites,
        crate::handlers::rewrites::add_rewrite,
        crate::handlers::rewrites::delete_rewrite,
        crate::handlers::upstream::get_upstream_config,
        crate::handlers::upstream::update_upstream_config,
        crate::handlers::upstream::test_upstream_servers,
        crate::handlers::cache::flush_cache,
        crate::handlers::cache::invalidate_cache,
        crate::handlers::ha::get_ha_status,
        crate::handlers::ha::get_ha_slaves,
        crate::handlers::ha::trigger_ha_resync,
        crate::handlers::auth_handlers::login,
        crate::handlers::auth_handlers::verify_totp,
        crate::handlers::auth_handlers::logout,
        crate::handlers::auth_handlers::get_totp_setup,
        crate::handlers::auth_handlers::enable_totp,
        crate::handlers::auth_handlers::disable_totp,
        crate::handlers::auth_handlers::list_tokens,
        crate::handlers::auth_handlers::create_token,
        crate::handlers::auth_handlers::delete_token,
        crate::handlers::config::get_config,
        crate::handlers::config::update_config,
        crate::handlers::config::reload_config,
        crate::handlers::config::download_backup,
        crate::handlers::config::prepare_restore,
        crate::handlers::config::confirm_restore,
    ),
    components(
        schemas(
            crate::models::StatusResponse,
            crate::models::StatsQuery,
            crate::models::FilterListDto,
            crate::models::AddFilterListRequest,
            crate::models::UpdateFilterListRequest,
            crate::models::CustomRulesDto,
            crate::models::FilterCheckRequest,
            crate::models::FilterCheckResponse,
            crate::models::ClientDto,
            crate::models::ClientGroupDto,
            crate::models::RewriteDto,
            crate::models::AddRewriteRequest,
            crate::models::UpstreamConfigDto,
            crate::models::UpstreamTestRequest,
            crate::models::UpstreamTestItem,
            crate::models::UpstreamTestResponse,
            crate::models::InvalidateCacheQuery,
            crate::models::GenericMessageResponse,
            crate::models::ConfigResponse,
            crate::models::UpdateConfigRequest,
            crate::models::BackupMetadata,
            crate::models::RestorePreparedResponse,
            crate::models::RestoreConfirmRequest,
            crate::models::LoginRequest,
            crate::models::LoginResponse,
            crate::models::TotpVerifyRequest,
            crate::models::TotpConfirmRequest,
            crate::models::CreateTokenRequest,
            crate::models::HaStubResponse,
            crate::models::HaStatusResponse,
            crate::models::HaSlaveSummary,
            crate::models::HaSlaveStatsSummary,
            crate::models::HaResyncResponse,
            crate::auth::token::Role,
            crate::auth::token::ApiTokenMeta,
            crate::auth::token::CreateTokenResponse,
            crate::auth::totp::TotpSetupResponse,
            crate::error::ProblemDetails,
            sito_stats::GlobalStats,
            sito_stats::ClientStats,
            sito_stats::UpstreamStats,
            sito_stats::QueryLogEntry,
            sito_stats::QueryLogPage,
            sito_stats::QueryLogFilter,
        )
    ),
    tags(
        (name = "System", description = "System status and health"),
        (name = "Stats", description = "Query statistics and metrics"),
        (name = "QueryLog", description = "Historical query logs and live streaming"),
        (name = "Filtering", description = "Blocklists, allowlists, and custom rules"),
        (name = "Clients", description = "Client mapping and policy groups"),
        (name = "Rewrites", description = "Custom DNS rewrites"),
        (name = "Upstream", description = "Upstream DNS resolvers and latency probing"),
        (name = "Cache", description = "Response cache operations"),
        (name = "Config", description = "Configuration persistence, hot-reload, backup and restore"),
        (name = "Auth", description = "Authentication, sessions, TOTP 2FA, and API tokens"),
        (name = "HA", description = "High Availability replication (Phase M8)")
    ),
    info(
        title = "sito DNS Administrative API",
        version = "1.1.1",
        description = "Administrative REST API and OpenAPI 3.0 specification for the sito DNS server",
        license(name = "GPL-3.0-only")
    )
)]
pub struct ApiDoc;
